#!/bin/bash

WDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) # working dir
METADATA="${WDIR}/package/metadata.json"
VERSION=$(grep '"Version"' $METADATA | sed -E 's/^\s+".*": "(.*)",/\1/')

cd ${WDIR}/package
zip -r ../Luna3-${VERSION}.plasmoid *
cd ..
