#!/bin/bash

METADATA="package/metadata.json"
APPNAME=$(grep '"Id"' $METADATA | sed -E 's/^\s+".*": "(.*)",/\1/')
_basename=$(basename "$0")
_INSTALL_COMMAND=kpackagetool6


_SHORT_OPTIONS="h?i"
_LONG_OPTIONS="help,install"
_install=0


show_help() { echo "Usage: ${_basename} [OPTIONS]...
Upgrade plasmoid.

Options:
  -h, --help                display this help text and exit
  -i, --install             install instead of upgrading
"; }


#canonicalize options
_args=$(getopt \
    --longoptions $_LONG_OPTIONS \
    --name ${_basename} \
    --options $_SHORT_OPTIONS \
    -- "$@"
)
if [ $? != 0 ] ; then show_help ; exit 1 ;
else set -- $_args ; fi


# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
    '--install')    set -- "$@" '-i'   ;;
    '--help')       set -- "$@" '-h'   ;;
    *)              set -- "$@" "$arg" ;;
  esac
done


while getopts $_SHORT_OPTIONS opt; do
    case "$opt" in
    h | \? )
        show_help
        exit 0
        ;;
    i )
        _install=1
        ;;
    esac
done

if [ $_install = 1 ]; then
    $_INSTALL_COMMAND --type Plasma/Applet --install package
else
    $_INSTALL_COMMAND --type Plasma/Applet --upgrade package
fi

if [ $? != 0 ] ; then exit 1 ; fi

echo
echo '------------------------------------------------'
echo

plasmoidviewer -a $APPNAME
